# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('faves', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('faves', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='backend.Comment')),
            ],
        ),
    ]
