# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='url',
        ),
    ]
