# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_subcomment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='comment',
            name='subcomments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='backend.SubComment'),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
