# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170127_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subcomments',
        ),
        migrations.AddField(
            model_name='subcomment',
            name='subcomments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='backend.Comment'),
        ),
    ]
