# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170127_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcomment',
            old_name='subcomments',
            new_name='reply_to',
        ),
    ]
